# action.yml
name: 'MM EKS Helm Deploy'
description: 'Deploy a helm chart to EKS cluster.'
branding:
    icon: anchor
    color: yellow
inputs:
    aws-secret-access-key:
        description: 'AWS credentials used to login to eks.'
        required: true
    aws-access-key-id:
        description: 'AWS credentials used to login to eks.'
        required: true
    aws-region:
        description: 'AWS region to use (default: us-west-2)'
        required: true
        default: us-west-2
    cluster-name:
        description: 'EKS cluster name.'
        required: true
    cluster-role-arn:
        description: 'EKS cluster admin role arn.'
        required: false
    config-files:
        description: 'Comma separates list of helm values files.'
        required: false
    namespace:
        description: 'Kubernetes namespace to use.'
        required: false
    values:
        description: 'Comma separated list of value sets for helms. e.x: key1=value1,key2=value2'
        required: false
    name:
        description: 'Name of the helm deploy.'
        required: true
    chart-path:
        description: 'The path of the chart.'
        required: true
        default: 'helm/'
    version:
        description: 'Chart Version'
        required: false
    timeout:
        description: 'Timeout for the job.'
        required: true
        default: 5m0s
    repo-username:
        description: 'helm repo username'
        required: false
    repo-password:
        description: 'helm repo password'
        required: false
    repo:
        description: 'helm repo'
        required: false
    atomic:
        description: 'Whether the upgrade should be atomic'
        required: false
        default: true
    wait:
        description: 'Whether the upgrade should wait for all resources to be Ready before completing'
        required: false
        default: 'true'
    debug:
        description: 'Whether to enable debug logging'
        required: false
        default: 'false'
    extra-args:
        description: 'Any extra command line arguments to pass to Helm'
        required: false

runs:
    using: 'docker'
    # image: 'docker://peymanmo/eks-helm-deploy:v2'
    image: Dockerfile
    env:
        ATOMIC: ${{ inputs.atomic }}
        AWS_REGION: ${{ inputs.aws-region }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        CLUSTER_ROLE_ARN: ${{ inputs.cluster-role-arn }}
        DEBUG: ${{ inputs.debug }}
        DEPLOY_CONFIG_FILES: ${{ inputs.config-files }}
        DEPLOY_NAMESPACE: ${{ inputs.namespace }}
        DEPLOY_VALUES: ${{ inputs.values }}
        DEPLOY_NAME: ${{ inputs.name }}
        DEPLOY_CHART_PATH: ${{ inputs.chart-path }}
        EXTRA_ARGS: ${{ inputs.extra-args }}
        REPO_USERNAME: ${{ inputs.repo-username }}
        REPO_PASSWORD: ${{ inputs.repo-password }}
        REPO: ${{ inputs.repo }}
        TIMEOUT: ${{ inputs.timeout }}
        VERSION: ${{ inputs.version }}
        WAIT: ${{ inputs.wait }}
